---
title: "R Notebook"
output: html_notebook
---

```{r}
# Install scripts and source packages
# install.packages("devtools")
# library(devtools)
# devtools::install_github("kingaa/pomp")
# devtools::install_github("krlmlr/here")
# install.packages("tidyverse")
library(pomp2)
library(here)
library(dplyr)
library(ggplot2)
library(zoo)
```

```{r}
# Load data
# TODO: do we check the data sources? Where are they coming from?
dzzDataFile <- here::here("cities", "Brazil", "all data.csv")
brazil_measles <- data.frame(read.csv(dzzDataFile,header=TRUE)) %>%
  filter(dzz == "measles" & gender == "both" & year %in% 1979:1995) %>%
  mutate(measles0_9 = under1 + one_4 + five_9)
brazil_population = data.frame(read.csv(
  here::here("cities","Brazil populations.csv"),header=TRUE)) %>%
  filter(location == "Brazil" & gender == "both" & year %in% 1979:1995) %>%
  mutate(pop0_9 = X0_4 + X5_9) # TODO: check if this sum is right
# given that 0_1 + 1_4 does not equal 0_4
```

```{r}
# Define POMP model. Reusing the model in
# https://kingaa.github.io/short-course/measles/measles.html#the-partially-observed-markov-process-model,
# which is from He, Ionides, & King, J. R. Soc. Interface (2010).
birthrate = 50000
pop = 3390000
# see https://en.wikipedia.org/wiki/Compartmental_models_in_epidemiology to
# understand the SIR model setup, the definitions of concepts like transmission/
# contact rate and force of infection and the conventional variable names (e.g.
# beta, gamma)
rproc <- Csnippet(stringr::str_interp("
  double beta, br, seas, foi, dw, births;
  double rate[18], trans[18];
  double birthrate = $[d]{birthrate};
  double pop = $[d]{pop};

  // cohort effect
  if (fabs(t-floor(t)-251.0/365.0) < 0.5*dt)
    br = cohort*birthrate/dt + (1-cohort)*birthrate;
  else
    br = (1.0-cohort)*birthrate;

  // term-time seasonality
  t = (t-floor(t))*365.25;
  if ((t>=7&&t<=100) || (t>=115&&t<=199) || (t>=252&&t<=300) || (t>=308&&t<=356))
      seas = 1.0+amplitude*0.2411/0.7589;
    else
      seas = 1.0-amplitude;

  // transmission rate
  beta = R0*(gamma+mu)*seas;
  // expected force of infection
  foi = beta*pow(I+iota,alpha)/pop;
  // white noise (extrademographic stochasticity)
  dw = rgammawn(sigmaSE,dt);

  rate[0] = foi*dw/dt;  // stochastic force of infection
  rate[1] = beta_i;             // infection of S w/ non-mz
  rate[2] = gamma;        // rate of entering immune amnesia
  rate[3] = beta_i;             // coinfection of I w/ non-mz
  rate[4] = phi;             // recovery
  rate[5] = beta_i;             // coinfection of A w/ non-mz
  rate[6] = beta_i;             // infection of R w/ non-mz
  rate[7] = r;             // recovery from non-mz infection S_i -> S
  rate[8] = foi*dw/dt;  // stochastic force of infection
  rate[9] = mu;             // S death from non-mz
  rate[10] = r;             // recovery from non-mz infection I_i -> I
  rate[11] = gamma;  // rate of entering immune amnesia
  rate[12] = 100 * mu;             // I death from mz + non-mz co-infection
  rate[13] = r;            // recovery from non-mz infection A_i -> A
  rate[14] = phi;             // recovery from measles
  rate[15] = 10 * mu;           // A death from mz amnesia + non-mz co-infection
  rate[16] = r;             // recovery from non-mz infection R_i -> R
  rate[17] = mu;             // R death from non-mz

  // Poisson births
  births = rpois(br*dt);

  // transitions between classes
  reulermultinom(2,S,&rate[0],dt,&trans[0]);
  reulermultinom(2,I,&rate[2],dt,&trans[2]);
  reulermultinom(2,A,&rate[4],dt,&trans[4]);
  reulermultinom(1,R,&rate[6],dt,&trans[6]);
  reulermultinom(3,S_i,&rate[7],dt,&trans[7]);
  reulermultinom(3,I_i,&rate[10],dt,&trans[10]);
  reulermultinom(3,A_i,&rate[13],dt,&trans[13]);
  reulermultinom(2,R_i,&rate[16],dt,&trans[16]);

  // A way to debug these update eqns: ensure each trans[i] (besides birth and
  // death) is counted twice, once positively and once negatively. An outflow(-)
  // from one compartment must be matched by an inflow(+) to another.
  S += births   - trans[0] - trans[1] + trans[7];
  I += trans[0] - trans[2] - trans[3] + trans[10];
  A += trans[2] - trans[4] - trans[5] + trans[13];
  R += trans[4] - trans[6] + trans[16];
  S_i += trans[1] - trans[7] - trans[8] - trans[9];
  I_i += trans[3] + trans[8] - trans[10] - trans[11] - trans[12];
  A_i += trans[5] + trans[11] - trans[13] - trans[14] - trans[15];
  R_i += trans[6] + trans[14] - trans[16] - trans[17];
  S_I += trans[0] + trans[8];  // for tracking immunomodulated population
  nonmz_D += trans[9] + trans[15] + trans[17];
  W += (dw - dt)/sigmaSE;  // standardized i.i.d. white noise
  C += trans[2] + trans[11];           // true incidence
"))
initlz <- Csnippet(stringr::str_interp("
  double pop = $[d]{pop};
  double m = pop/(S_0+I_0+A_0+R_0);
  S = nearbyint(m*S_0);
  I = nearbyint(m*I_0);
  A = nearbyint(m*A_0);
  R = nearbyint(m*R_0);
  S_i = I_i = A_i = R_i = 0;
  S_I = nonmz_D = 0;
  W = 0;
  C = 0;
"))
dmeas <- Csnippet("
  double m = rho*C;
  double v = m*(1.0-rho+psi*psi*m);
  double tol = 1.0e-18;
  if (cases > 0.0) {
    lik = pnorm(cases+0.5,m,sqrt(v)+tol,1,0)-pnorm(cases-0.5,m,sqrt(v)+tol,1,0)+tol;
  } else {
    lik = pnorm(cases+0.5,m,sqrt(v)+tol,1,0)+tol;
  }
")
rmeas <- Csnippet("
  double m = rho*C;
  double v = m*(1.0-rho+psi*psi*m);
  double tol = 1.0e-18;
  cases = rnorm(m,sqrt(v)+tol);
  if (cases > 0.0) {
    cases = nearbyint(cases);
  } else {
    cases = 0.0;
  }
")
sim_dt = 1/365.25
times <- seq(from=1979, to=1995, by=sim_dt)
paramnames <- c("R0","mu","sigma","gamma","phi","alpha","iota",
                "rho","sigmaSE","psi","cohort","amplitude",
                "S_0","I_0","A_0","R_0",
                "beta_i","r")
sir <- pomp(data = NULL, times = times, t0 = 2*times[1]-times[2],
            rprocess=euler(rproc,delta.t=sim_dt),
            rinit=initlz,
            dmeasure=dmeas,
            rmeasure=rmeas,
            obsnames = "cases",
            accumvars=c("C","W","S_I","nonmz_D"),
            statenames=c("S","I","A","R","C","W","S_I",
                         "nonmz_D","S_i","I_i","A_i","R_i"),
            paramnames=paramnames)
# I estimate phi as 1 / (duration of proposed amnesia) = 1/(2 years) = 1/2. Mina
# et al. Science 2016 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4823017/)
# and https://www.nature.com/articles/s41467-018-07515-0 observe amnesia for at
# least 2 years, which means we need the A compartment to last on average at
# least 2 years; then, if we're modeling a country with low background of
# infectious disease, we'll observe mortality due to amnesia spread out over the
# 2 years; if we're modeling a country with high background of infectious
# disease, we'll observe mortality due to amnesia more quickly than 2 years.
# Then 2 years is a necessary lower bound on average duration in A. Relevant
# quote from the Nature article: "The disease [measles] is associated with a
# transient immune suppression and increased risk of childhood morbidity and
# mortality for a period of more than 2 years."
# These are estimated for London in He, Ionides, & King, J. R. Soc. Interface
# (2010).
mle = c(loglik=-3804.9,
        loglik.sd=0.16,
        mu=5/100000., # based on Fig 1 in
                      # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4823017
        delay=4,
        sigma=28.9,
        gamma=30.4,
        phi=0.1, #TODO: try different values
        rho=0.488,
        R0=56.8,
        amplitude=0.554,
        alpha=0.976,
        iota=2.9,
        cohort=0.557,
        psi=0.116,
        S_0=0.0297,
        E_0=5.17e-05,
        I_0=5.14e-05,
        A_0=5e-05,
        R_0=0.97,
        sigmaSE=0.0878,
        beta_i=52, # once per week
        r=26 # once per 2 weeks
)
mle[paramnames] -> theta
```

```{r}
# Run and plot simulation
# Estimate gamma based on infectious period of measles estimated at 6-7 days:
# "Measles virus is shed from the nasopharynx beginning with the prodrome until
# 3–4 days after rash onset. The incubation period of measles, from exposure to
# prodrome, averages 10–12 days. From exposure to rash onset averages 14 days
# (range, 7–21 days)." Then 1/gamma is about 1/52 of a year, or gamma=52.
# beta = gamma * R_0 = 52 * 15 = 780.
# https://www.cdc.gov/vaccines/pubs/pinkbook/downloads/meas.pdf
# Brazil simulation
sir %>%
  # simulate(params=c(Beta=1.5,gamma=1,rho=0.9,N=2600),
  simulate(params=theta,
           # can make N adj w/ time
           # change nsim back to 20
           nsim=10,format="data.frame", seed = 96) -> sims1
# US/UK simulation: has lower rates of infection and lower rate of
# leaving amnesia
sir %>%
  simulate(params=theta %>% replace(c('beta_i', 'phi'), c(13, 0.01)),
           nsim=10,format="data.frame", seed = 96) -> sims2
# Name simulations here.
sims = bind_rows(`beta_i=52,phi=0.1`=sims1, `beta_i=13,phi=0.1`=sims2,
                 .id = 'simulation_params')
sims %>%
  ggplot()+
  geom_line(mapping = aes(x=time,y=cases))+
  geom_line(mapping = aes(x=time,y=300*nonmz_D), alpha=0.4)+
  scale_y_continuous(sec.axis = sec_axis(~ . *1/300.,
                                         name = "non-mz deaths"))+
  facet_wrap(~simulation_params+.id)
```

```{r}
# Find amnesia time length that best correlates past measles incidence with
# current non-measles mortality.
# First condense simulation dataframe into observations dataframe, where
# observations are made only sparsely, e.g. every quarter-year vs. everyday.
obs_period_len = 0.25
obs = sims %>%
  mutate(end_obs_period = ceiling(time/obs_period_len) * obs_period_len) %>%
  select(-time) %>%
  group_by(simulation_params, .id, end_obs_period) %>%
  group_by(n_sim = n(), add = TRUE) %>%
  summarise_all(sum) %>%
  filter(n_sim > 1) # throw out periods that don't span full obs_period_len

compute_inc_mort_r2s = function(obs, roll_S_I_len_yrs, roll_nonmz_D_len_yrs) {
  # Compute rolling windows of measles incidence and non-measles mortality to
  # estimate immunomodulated and non-measles mortality populations.
  roll_S_I_len_obs = floor(roll_S_I_len_yrs/obs_period_len)
  roll_nonmz_D_len_obs = floor(roll_nonmz_D_len_yrs/obs_period_len)
  inc_mort = obs %>% group_by(simulation_params, .id) %>%
    group_modify(~ .x %>%
                   transmute(mz_immunomodulated = c(rep(NA, roll_S_I_len_obs-1),
                                          rollsum(.x %>% select(S_I),
                                                  roll_S_I_len_obs)),
                             # this indexing ensures period in which mortality is
                             # counted doesn't overlap with period in which past
                             # incidence enters immunomodulated population; one
                             # can allow overlap by shifting rollsum up or down
                             # (c(rollsum[-1], NA...) -> c(rollsum, 1 fewer NA) ->
                             # c(rollsum[-2], 1 more NA...) and correspondingly
                             # updating nonmz_D_s and nonmz_D_e
                             non_mz_mort = c(rollsum(.x %>% select(nonmz_D),
                                                  roll_nonmz_D_len_obs)[-1],
                                          rep(NA, roll_nonmz_D_len_obs)),
                             S_I_s = end_obs_period - roll_S_I_len_yrs,
                             S_I_e = end_obs_period,
                             nonmz_D_s = end_obs_period,
                             nonmz_D_e = end_obs_period + roll_nonmz_D_len_yrs,
                             )) %>%
    filter(row_number() %% roll_nonmz_D_len_obs == 0) %>% # mortality window
    na.omit()
  # Compute r^2s between immunomodulated and non-measles mortality populations.
  r2s = inc_mort %>%
    group_by(simulation_params, .id) %>%
    summarise(r2 = cor(mz_immunomodulated, non_mz_mort)^2)
  return(list(inc_mort=inc_mort, r2s=r2s))
}

roll_S_I_lens_yrs = 1:16 * obs_period_len
roll_nonmz_D_len_yrs = 1 * obs_period_len
inc_mort_r2s = purrr::map(roll_S_I_lens_yrs, function(roll_S_I_len_yrs) {
  compute_inc_mort_r2s(obs, roll_S_I_len_yrs, roll_nonmz_D_len_yrs)
}) %>% setNames(roll_S_I_lens_yrs)

# Scatter plot immunomodulated and non-measles mortality populations.
inc_mort_r2s[[12]]$inc_mort %>% ggplot(aes(x=mz_immunomodulated/1000.,
                                           y=non_mz_mort/1000.)) +
  geom_point(size=0.1) +
  facet_wrap(~simulation_params+.id) +
  xlab(paste0(signif(roll_S_I_lens_yrs[12], 2), "-yr mz incidence (1000s)")) +
  ylab(paste0("following ", signif(roll_nonmz_D_len_yrs, 2),
              "-yr non-mz mortality (1000s)"))
```

```{r}
# Plot mz incidence-non mz mortality correlations vs. time periods covering
# immunomodulated populations. First combine the r2 dataframes and calculate
# medians across random simulations, within simulation params:
r2s = bind_rows(inc_mort_r2s %>% purrr::map('r2s'), .id = 'roll_S_I_len_yrs')
r2_medians = r2s %>% group_by(simulation_params, roll_S_I_len_yrs) %>%
  summarise(r2 = median(r2))
# Plot them.
ggplot(mapping = aes(x=roll_S_I_len_yrs, y=r2, group=simulation_params)) +
  geom_point(data=r2s, size=0.01) +
  geom_line(data=r2_medians) +
  facet_wrap(~simulation_params, ncol = 1)
```